version: '3.3'
services:
  mongo:
    command: mongod
    image: mongo:3.6
    ports:
      - "27017:27017" # map port to none standard port, to avoid conflicts with locally installed mongodb.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  bot:
    build:
      context: "./bot"
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./bot/src
        target: /app/src
    ports:
      - "3001:3001"
    depends_on:
      - mongo
