---
- name: Setup server
  hosts: deploy
  become: true
  vars_files:
    - ["vars/main.yml"]
  roles:
    - { role: angstwad.docker_ubuntu}
  tasks:
    - name: Create base directories
      file: path="{{item}}" state=directory
      with_items:
        - "{{app_home}}"
        - "{{mongo_data_dir}}"

    - name: pull mongo docker image
      docker_image:
        state: present
        force: yes
        name: "mongo:3.6.3"
        tag: "3.6.3"
      tags:
        - mongo

    - name: run mongo using docker
      docker_container:
        name: mongo
        image: mongo:3.6.3
        command: mongod
        state: started
        restart_policy: always
        volumes:
          - "{{mongo_data_dir}}:/data/db"
        ports:
          - "127.0.0.1:27017:27017"
      tags:
        - mongo